//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotehet.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Quitance = new HashSet<Quitance>();
            this.SummaryTable = new HashSet<SummaryTable>();
        }
    
        public int id { get; set; }
        public Nullable<int> pasport { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public Nullable<int> idNumber { get; set; }
        public Nullable<int> place { get; set; }
        public string zachem { get; set; }
        public string fromOrganizationName { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public Nullable<int> ph_number { get; set; }
    
        public virtual Number Number { get; set; }
        public virtual ICollection<Quitance> Quitance { get; set; }
        public virtual ICollection<SummaryTable> SummaryTable { get; set; }
    }
}
