//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotehet.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aaaaHotelEntities : DbContext
    {
        public aaaaHotelEntities()
            : base("name=aaaaHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Client { get; set; }
        public DbSet<Number> Number { get; set; }
        public DbSet<NumberClass> NumberClass { get; set; }
        public DbSet<Quitance> Quitance { get; set; }
        public DbSet<SummaryTable> SummaryTable { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
