//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotehet.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number
    {
        public Number()
        {
            this.Client = new HashSet<Client>();
            this.Quitance = new HashSet<Quitance>();
            this.SummaryTable = new HashSet<SummaryTable>();
        }
    
        public int id { get; set; }
        public Nullable<int> idNumberCLass { get; set; }
        public Nullable<int> amountPlaces { get; set; }
        public Nullable<bool> isFree { get; set; }
        public Nullable<System.DateTime> dateRelace { get; set; }
        public Nullable<decimal> dailyPrice { get; set; }
    
        public virtual ICollection<Client> Client { get; set; }
        public virtual NumberClass NumberClass { get; set; }
        public virtual ICollection<Quitance> Quitance { get; set; }
        public virtual ICollection<SummaryTable> SummaryTable { get; set; }
    }
}
