//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotehet.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quitance
    {
        public int id { get; set; }
        public Nullable<int> idNumber { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Number Number { get; set; }
    }
}
